[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "ds-test=lib/forge-std/lib/ds-test/src",
    "forge-std=lib/forge-std/src",
]
optimizer = true
optimizer_runs = 200

solc_version = "0.8.28"

[rpc_endpoints]
localhost = "http://localhost:8545"
polygon_mainnet = "${RPC_URL_MAINNET}"


[test]
match_path = "test/*.t.sol"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
