[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path = "cache" 
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "ds-test=lib/forge-std/lib/ds-test/src",
    "forge-std=lib/forge-std/src",
]
optimizer = true
optimizer_runs = 200

solc_version = "0.8.28"

[rpc_endpoints]
localhost = "http://localhost:8545"
polygon_mainnet = "${RPC_URL_MAINNET}"
polygon_testnet = "${RPC_URL_TESTNET}"

[etherscan]
polygon_mainnet = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
polygon_testnet = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.amoy.polygonscan.com/api" }


[profile.test]
match_path = "test/*.t.sol"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
